# Generated by Django 2.2 on 2019-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190409_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='json',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
