# Generated by Django 2.1.7 on 2019-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('paradigm', models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('IMPERATIVE', 'Imperative')], default='IMPERATIVE', max_length=10)),
                ('is_oo', models.BooleanField()),
            ],
        ),
    ]
